TARGET     =
MODE       = exe
OBJS       = $(TARGET).obj
STACKSIZE  = 0x1000000 # 16MB (default)

INCPATH    = ../tolset/z_tools/win32/
CC1OPT     = -Dmain=main0
include ../tolset/z_tools/com_mak.txt

# tolset08‘Î‰žMakefile
